language: python

python:
  - 3.5

addons:
  apt:
    packages:
      - pyqt5-dev-tools

git:
  submodules: false

before_install:
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

script:
  - scripts/ci/deploy.sh
